"""Fixed messages: private exception values must never reach the console."""

MESSAGES = {
    "plan_inspection_failed": "Inspection could not finish. Review its operational failure before retrying.",
    "plan_input_unreadable": "Container information could not be read; this does not establish irrecoverability.",
    "plan_input_unsupported": "The input is unsupported by this recovery pipeline.",
    "plan_source_evidence": "Source initialization, access or stability findings prevent a safe recovery plan.",
    "plan_no_av_streams": "No eligible audio or video streams were found.",
    "plan_auxiliary_tracks": "Required auxiliary tracks cannot be preserved by this conversion. Review track-loss permission.",
    "plan_mp4_codec": "Selected codecs cannot be copied into MP4. Encoding may be required.",
    "plan_trim_range": "The selected trim range cannot be verified against source duration.",
    "plan_pixel_format": "This pixel format is not supported by the selected verified encoding profile.",
    "plan_interlaced": "Verified conversion of interlaced video is not supported by this profile.",
    "plan_hdr": "HDR/color preservation or tone mapping is not supported by this encoding profile.",
    "plan_dimensions": "This MP4 profile requires even frame dimensions.",
    "plan_audio_properties": "Audio sample rate or channel properties are missing or unsupported.",
    "plan_audio_layout": "This AAC profile cannot preserve the reported channel layout or sample rate.",
    "plan_audio_samples": "This audio sample format cannot be preserved by the lossless profile.",
    "retry_session_unavailable": "Continue/retry is unavailable in this session. Use a checkpoint created before the job, or choose a new empty destination.",
    "encoding_options_conflict": "Audio conversion options require Compatible SDR MP4 re-encoding. Choose that profile or disable the audio options; remux and preservation do not apply them.",
    "worker_cleanup_failed": "Worker shutdown could not be confirmed. Processing stopped; review local session storage before continuing.",
    "migration_selection": "Select exactly one source folder for migration. [MIG-SELECTION]",
    "migration_workspace_overlap": "Source overlaps the workspace. Choose your media folder as Source and keep Workspace separate. [MIG-WORKSPACE]",
    "migration_output_overlap": "Source and output overlap. Choose an output folder outside the source folder. [MIG-OUTPUT]",
    "migration_software_overlap": "Source overlaps the VideoMate software folder. Choose a separate source folder. [MIG-SOFTWARE]",
    "migration_storage_overlap": "Source overlaps the settings, diagnostics or logs location. Choose separate storage in Settings. [MIG-STORAGE]",
    "migration_not_folder": "The selected source is missing or is not a folder. Choose the source folder again. [MIG-FOLDER]",
    "migration_empty": "The selected source contains no files. Choose the folder containing your originals. [MIG-EMPTY]",
    "migration_name_conflict": "Source names conflict after case or Unicode normalization. Resolve duplicate names locally or migrate separate subfolders. [MIG-NAMES]",
    "migration_link": "The source contains a link or reparse point. Migration requires ordinary local files and folders. [MIG-LINK]",
    "migration_network": "The source is a network location. Select an approved local source folder. [MIG-NETWORK]",
    "migration_source_location": "The source is inside a software repository, known sync folder or mapped network drive. Select approved local storage. [MIG-LOCATION]",
    "migration_mount": "The source contains a nested mount or another filesystem. Select that folder as a separate source. [MIG-MOUNT]",
    "migration_special_file": "The source contains a special entry such as a device or socket. Select a folder containing ordinary files. [MIG-FILE-TYPE]",
    "migration_access": "A source file or folder could not be accessed. Check local permissions and keep the source unchanged while starting. [MIG-ACCESS]",
    "migration_names_required": "Migration preserves local filenames and folders. Enable the explicit local-output names option for Sensitive migration; diagnostics still exclude names.",
    "migration_output_not_empty": "A new migration needs an empty destination folder. Continue a stopped job in this app session, use its prior Private resume checkpoint, or choose a new empty folder. Nothing was overwritten. [MIG-DESTINATION]",
    "rate_target_unavailable": "The selected bitrate or size target cannot be estimated for this input. Choose Auto or Quality mode.",
    "cleanup_incomplete": "Some session-created temporary files could not be removed. Review private storage locally; no paths were displayed.",
    "passphrase_required": "Private resume requires a passphrase of 12-1024 characters. It is never saved in settings or logs.",
    "checkpoint_invalid": "The private checkpoint could not be authenticated or validated. Check the ID and passphrase.",
    "checkpoint_policy_changed": "Choose the same processing options and software version as the checkpoint, or start a new job.",
    "checkpoint_sources_changed": "The reselected files do not match the private checkpoint, or an input changed while matching. Start a new job for changed inputs.",
    "cleanup_confirmation": "Select individual files and confirm the exact cleanup action. No files were changed.",
    "input_changed": "An input changed during the operation. It was not removed.",
    "gui_unavailable": "The native GUI requires Python with Tk and a graphical session. The CLI is available without Tk.",
    "job_invalid": "The local job is missing or invalid. No private details were displayed.",
    "job_busy": "This job is already in use by another local process.",
    "recovery_blocked": "This recovery plan cannot preserve the required properties or exceeds the selected policy.",
    "disk_limit": "The candidate exceeds its disk budget or available storage is insufficient.",
    "dependency_unavailable": "The local FFmpeg bundle is missing, incompatible, or failed its integrity check. Run the explicit dependency installer, then doctor.",
    "settings_invalid": "Settings could not be loaded or saved. Check the values and choose a local settings file.",
    "settings_location": "Choose an absolute local settings filename, not a folder or sync location. Leave Settings file blank to use the default. [SETTINGS-LOCATION]",
    "selection_required": "Select local files before starting this operation.",
    "privacy_downgrade": "This saved job uses Sensitive: Yes. Its privacy setting cannot be reduced when reusing its inputs.",
    "invalid_arguments": "Invalid arguments. Use --help for command syntax.",
    "invalid_export": "Diagnostic validation failed. No input details were displayed.",
    "export_too_large": "The diagnostic export exceeds the size limit.",
    "backend_unavailable": "A configured backend could not be started.",
    "backend_invalid": "The configured backend is not an eligible executable.",
    "ffmpeg_process_failed": "FFmpeg exited without completing this worker step. Review its stage, exit code, classified messages and subsequent verification.",
    "workspace_rejected": "Workspace or storage could not be prepared. Use a writable local folder outside software and sync locations; resolve any files blocking required folders. [WORKSPACE-STORAGE]",
    "input_rejected": "The input is not an eligible explicitly selected local file.",
    "output_exists": "The output destination already exists; it was not replaced.",
    "source_read_failed": "A source could not be read. Check local access and drive health. No source details were displayed.",
    "output_write_failed": "An output could not be written. Check the output drive and available space.",
    "copy_verification_failed": "A copied candidate could not be verified byte for byte. It was not published.",
    "output_publish_failed": "A verified candidate could not be published. Check the output drive and local access.",
    "output_access_denied": "Output access was denied or the drive is read-only. Choose writable local output storage.",
    "output_filesystem_unsupported": "The output filesystem cannot perform safe exclusive publication, or staging and output are on different filesystems. Choose another local output folder.",
    "output_path_too_long": "An output path exceeds the filesystem limit. Choose a shorter output root or migrate a smaller subtree.",
    "output_busy": "An output is locked by another local process. Release the lock or choose another output folder.",
    "resume_storage_changed": "Storage identity changed. Reselect the source and output folders and review the job before resuming; nothing was overwritten.",
    "resume_output_conflict": "A previously published output changed or an untracked output occupies its destination. Keep it for review; it was not overwritten or duplicated.",
    "io_error": "A local filesystem operation failed. No path was displayed.",
    "internal_error": "The operation failed. No private error details were displayed.",
    "cancelled": "Operation cancelled.",
}


class VideoMateError(Exception):
    def __init__(self, code: str):
        self.code = code if code in MESSAGES else "internal_error"
        super().__init__(MESSAGES[self.code])
